COLUMNS:
  CRIM: float64
  ZN: float64 
  INDUS: float64
  CHAS: int64
  NOX: float64
  RM: float64
  AGE: float64
  DIS: float64
  RAD: int64
  TAX: int64
  PTRATIO: float64
  B: float64
  LSTAT: float64
  BIAS_COL: int64


TARGET_COLUMN:
  name : MEDV